# docker-compose up -d --build
# based on https://medium.com/@lojorider/docker-with-cgi-perl-a4558ab6a329
# docker exec -it webtrees_web bash
# docker exec -it webtrees_php bash
# activate the db section or the network section depending on whether to use it on desktop or raspberry

version: '3'
services:
    web:
        container_name: webtrees_web
        restart: always
        build:
            context: .
        volumes:
            - ./weblog:/var/log/nginx/web
            - /richi/Privat/Data/Webtrees-Data:/var/www/data
        ports:
            - "8088:80"

    php:
        container_name: webtrees_php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - /richi/Privat/Data/Webtrees-Data:/var/www/data
           
networks:
   default:
       external:
          name: RichiNet
